"use client";

import { useEffect, useRef, useState } from "react";
import { BarVisualizer, LiveKitRoom, RoomAudioRenderer, useConnectionState, useVoiceAssistant, VoiceAssistantControlBar } from "@livekit/components-react";
import { ConnectionState } from "livekit-client";
import { ArrowUpRight, AudioLines, Circle, Cpu, Mic, Radio, ShieldCheck } from "lucide-react";
import "@livekit/components-styles";

type CoreMode = "idle" | "connecting" | "listening" | "speaking";
type Node = { x: number; y: number; z: number; phase: number };
const energy: Record<CoreMode, number> = { idle: .55, connecting: .72, listening: .9, speaking: 1 };

function NeuralCore({ mode = "idle" }: { mode?: CoreMode }) {
  const ref = useRef<HTMLCanvasElement>(null); const pointer = useRef({ x: 0, y: 0 });
  useEffect(() => {
    const canvas = ref.current; const ctx = canvas?.getContext("2d"); if (!canvas || !ctx) return;
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const count = window.matchMedia("(max-width: 700px)").matches ? 34 : 58;
    const nodes: Node[] = Array.from({ length: count }, (_, i) => { const a = i / count * Math.PI * 2.1; const r = .22 + Math.sqrt((i + 3) / count) * .72; return { x: Math.cos(a) * r, y: Math.sin(a * 1.71) * r * .72, z: Math.sin(a * .77) * r, phase: i * .61 }; });
    let id = 0; const draw = (time: number) => { const rect = canvas.getBoundingClientRect(); const dpr = Math.min(devicePixelRatio || 1, 2); const w = Math.floor(rect.width * dpr), h = Math.floor(rect.height * dpr); if (canvas.width !== w || canvas.height !== h) { canvas.width = w; canvas.height = h; } ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.clearRect(0, 0, rect.width, rect.height); const t = reduce ? .7 : time * .00016; const scale = Math.min(rect.width, rect.height) * .43; const c = Math.cos(t + pointer.current.x * .14), s = Math.sin(t + pointer.current.x * .14); const mapped = nodes.map(n => { const x = n.x * c - n.z * s, z = n.x * s + n.z * c, y = n.y * Math.cos(.42 + pointer.current.y * .09) - z * Math.sin(.42 + pointer.current.y * .09), depth = (z + 1.25) / 2.5; return { x: rect.width / 2 + x * scale, y: rect.height / 2 + y * scale, depth, n }; });
      ctx.lineCap = "round"; for (let i = 0; i < mapped.length; i++) for (let j = i + 1; j < mapped.length; j++) { const a = mapped[i], b = mapped[j], d = Math.hypot(a.n.x-b.n.x, a.n.y-b.n.y, a.n.z-b.n.z); if (d > .39) continue; ctx.strokeStyle = `rgba(66,193,238,${(1-d/.39)*.3*((a.depth+b.depth)/2)*energy[mode]})`; ctx.lineWidth = .45 + ((a.depth+b.depth)/2)*.75; ctx.beginPath(); ctx.moveTo(a.x,a.y); ctx.lineTo(b.x,b.y); ctx.stroke(); }
      mapped.sort((a,b)=>a.depth-b.depth).forEach(({x,y,depth,n}) => { const r = (1.1 + depth*2.45) * (.7 + Math.sin(t*6+n.phase)*.3*energy[mode]); ctx.fillStyle = `rgba(141,229,255,${.28+depth*.66})`; ctx.beginPath(); ctx.arc(x,y,r,0,Math.PI*2); ctx.fill(); }); if (!reduce) id = requestAnimationFrame(draw); };
    id = requestAnimationFrame(draw); return () => cancelAnimationFrame(id);
  }, [mode]);
  return <div className="neural-core" onPointerMove={e=>{const b=e.currentTarget.getBoundingClientRect();pointer.current={x:(e.clientX-b.left)/b.width-.5,y:(e.clientY-b.top)/b.height-.5};}} onPointerLeave={()=>{pointer.current={x:0,y:0};}} role="img" aria-label="Interactive neural network visualization"><canvas ref={ref}/><div className="neural-halo"/><div className="neural-caption">NEURAL INTERFACE</div></div>;
}

export default function Home() {
  const [token, setToken] = useState(""); const [isConnecting, setIsConnecting] = useState(false);
  const connect = async () => { setIsConnecting(true); try { const r = await fetch(`/api/token?room=jarvis-room&username=user-${Math.floor(Math.random()*1000)}`); if (!r.ok) throw new Error("Unable to initialize"); setToken((await r.json()).token); } catch (e) { console.error(e); setIsConnecting(false); } };
  return <main className="app-shell"><div className="atmosphere"/><Header connected={!!token}/>{!token ? <Landing connecting={isConnecting} connect={connect}/> : <LiveKitRoom serverUrl={process.env.NEXT_PUBLIC_LIVEKIT_URL} token={token} connect audio video={false} className="live-session" onDisconnected={()=>{setToken("");setIsConnecting(false);}}><RoomAudioRenderer/><AssistantConsole/></LiveKitRoom>}</main>;
}
function Header({connected}:{connected:boolean}) { return <header className="topbar"><a href="#home" className="brand"><span className="brand-mark">J</span><span>JARVIS</span></a><nav><a href="#home">Home</a><a href="#assistant">Assistant</a><a href="#system">System</a></nav><div className="connection-status"><Circle/><span>{connected ? "Voice link active" : "System ready"}</span></div></header>; }
function Landing({connecting,connect}:{connecting:boolean;connect:()=>void}) { return <section id="home" className="hero"><div className="hero-copy"><p className="eyebrow"><span/> JARVIS // ONLINE</p><h1>Your intelligent<br/>digital assistant.</h1><p className="hero-description">A real-time voice interface engineered to listen, reason, and respond when you need it.</p><div className="hero-actions"><button className="button-primary" onClick={connect} disabled={connecting}><Mic size={17}/>{connecting ? "Establishing link" : "Start conversation"}</button><a className="button-secondary" href="#system">Explore system <ArrowUpRight size={16}/></a></div><p className="privacy-note"><ShieldCheck size={15}/> A private LiveKit voice session opens when you start.</p></div><div className="hero-visual"><NeuralCore mode={connecting ? "connecting" : "idle"}/></div><section id="system" className="system-strip"><div><span>INTERFACE</span><strong>Voice-first</strong></div><div><span>CONNECTION</span><strong>{connecting ? "Initialising" : "On demand"}</strong></div><div><span>SESSION</span><strong>LiveKit secured</strong></div></section></section>; }
function AssistantConsole() { const connection = useConnectionState(); const {state} = useVoiceAssistant(); const connected = connection === ConnectionState.Connected; const label = !connected ? "Connecting" : state === "speaking" ? "Speaking" : state === "listening" ? "Listening" : "Ready"; const mode:CoreMode = !connected ? "connecting" : state === "speaking" ? "speaking" : "listening"; return <section id="assistant" className="assistant-console"><aside className="console-side"><p className="eyebrow"><span/> LIVE SESSION</p><h1>Voice, without the noise.</h1><p>Jarvis joins the room and responds over an encrypted real-time audio connection.</p><div className="state-list"><Status icon={<Radio size={15}/>} label="Voice link" value={connected ? "Connected" : "Connecting"}/><Status icon={<Cpu size={15}/>} label="Assistant" value={label}/><Status icon={<AudioLines size={15}/>} label="Audio output" value={connected ? "Available" : "Waiting"}/></div></aside><div className="session-core"><NeuralCore mode={mode}/><div className="voice-state"><span className="state-dot"/>{label}</div><BarVisualizer state={state} barCount={9} options={{minHeight:6}} className="voice-bars"/><VoiceAssistantControlBar className="voice-controls"/></div></section>; }
function Status({icon,label,value}:{icon:React.ReactNode;label:string;value:string}) { return <div className="status-item"><span>{icon}</span><p>{label}<strong>{value}</strong></p></div>; }